app/DB/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.start, name='start'),
	url(r'^resetidseq/(?P<app_name>[A-ZÄÖÜa-zäöüß0-9_]+)/(?P<tabelle_name>[A-ZÄÖÜa-zäöüß0-9_]+)/{0,1}$', views.resetidseq, name='resetidseq'),
	url(r'^view/(?P<app_name>[A-ZÄÖÜa-zäöüß0-9_]+)/(?P<tabelle_name>[A-ZÄÖÜa-zäöüß0-9_]+)/{0,1}$', views.view, name='view'),
	url(r'^search/{0,1}$', views.search, name='search'),
	url(r'^dateien/{0,1}$', views.dateien, name='dateien'),
]

app/dioeDB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from Startseite import views as Startseite_views
import private_storage.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('Startseite.urls', namespace='Startseite')),
    url(r'^db/', include('DB.urls', namespace='DB')),
    # url(r'^korpusdb/', include('KorpusDB.urls', namespace='KorpusDB')),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}, name='dioedb_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('Startseite:start')}, name='dioedb_logout'),
    url(r'^change-password/$', 'django.contrib.auth.views.password_change', {'template_name': 'main/change-password.html'}, name='password_change'),
    url(r'^change-password/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'main/change-password-done.html'}, name='password_change_done'),
   	url(r'^sysstatus/{0,1}$', Startseite_views.sysStatusView, name='sysstatus'),
    url(r'^private-media/', include(private_storage.urls)),
]

app/DB/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User, Group

models.options.DEFAULT_NAMES +=('verbose_genus',) # m = maskulin, f = feminin, n = neutrum(default)

class sys_importdatei(models.Model):
	zu_app			= models.CharField(max_length=255																		, verbose_name="Zu App")
	zu_tabelle		= models.CharField(max_length=255																		, verbose_name="Zu Tabelle")
	zu_pk			= models.IntegerField(																					  verbose_name="Zu PK")
	datei			= models.CharField(max_length=255																		, verbose_name="Datei")
	zeit			= models.DateTimeField(																					  verbose_name="Zeit")
	erledigt		= models.BooleanField(									   default=False								, verbose_name="Erledigt")
	def __str__(self):
		return '{}->{}->{} <- {} ({}) Erledigt: {}"'.format(self.zu_app,self.zu_tabelle,self.zu_pk,self.datei,self.zeit,self.erledigt)
	class Meta:
		verbose_name = "Importdatei"
		verbose_name_plural = "Importdateien"
		ordering = ('zu_app','zu_tabelle','zu_pk',)
		default_permissions = ()
		permissions = (('dateien', 'Dateien anzeigen. (Zugriffsrechte für Verzeichnisse beachten!)'),('csvimport', 'CSV-Dateien importieren'),)

class user_verzeichniss(models.Model):
	user				= models.ForeignKey(User											, on_delete=models.CASCADE		, verbose_name="ID zu User")
	Verzeichniss		= models.CharField(max_length=511,			blank=True, null=True									, verbose_name="Verzeichniss")
	RECHTE_DATEN = (
		(0, 'Keine'),
		(1, 'Anzeigen'),
		(2, 'Anzeigen | Dateien hochladen und löschen'),
		(3, 'Anzeigen | Dateien hochladen und löschen | Unterverzeichnisse erstellen und löschen'),
		(4, 'Anzeigen | Dateien hochladen und löschen | Unterverzeichnisse erstellen und rekursiv löschen'),
	)
	Rechte				= models.PositiveIntegerField(				blank=True, null=True, choices=RECHTE_DATEN				, verbose_name="Rechte")
	def __str__(self):
		return "{} -> {} ({})".format(self.user,self.Verzeichniss,self.Rechte)
	class Meta:
		verbose_name = "Zugriffsrecht für Verzeichniss"
		verbose_name_plural = "Zugriffsrechte für Verzeichnisse"
		verbose_genus = "n"
		ordering = ('user',)
		default_permissions = ()

class group_verzeichniss(models.Model):
	group				= models.ForeignKey(Group											, on_delete=models.CASCADE		, verbose_name="ID zu Gruppe")
	Verzeichniss		= models.CharField(max_length=511,			blank=True, null=True									, verbose_name="Verzeichniss")
	RECHTE_DATEN_G = (
		(0, 'Keine'),
		(1, 'Anzeigen'),
		(2, 'Anzeigen | Dateien hochladen und löschen'),
		(3, 'Anzeigen | Dateien hochladen und löschen | Unterverzeichnisse erstellen und löschen'),
		(4, 'Anzeigen | Dateien hochladen und löschen | Unterverzeichnisse erstellen und rekursiv löschen'),
	)
	Rechte				= models.PositiveIntegerField(				blank=True, null=True, choices=RECHTE_DATEN_G			, verbose_name="Rechte")
	def __str__(self):
		return "{} -> {} ({})".format(self.group,self.Verzeichniss,self.Rechte)
	class Meta:
		verbose_name = "Zugriffsrecht für Verzeichniss"
		verbose_name_plural = "Zugriffsrechte für Verzeichnisse"
		verbose_genus = "n"
		ordering = ('group',)
		default_permissions = ()

class sys_filesystem(models.Model):
	def __str__(self):
		return '{}'.format(self.pk)
	class Meta:
		verbose_name = "Dateisystem"
		verbose_name_plural = "Dateisysteme"
		default_permissions = ()

class sys_user_addon(models.Model):
	user = models.OneToOneField(User														, on_delete=models.CASCADE		, verbose_name="ID zu User")
	last_visit = models.DateTimeField(																						  verbose_name="Zeit")

app/DB/views.py
from django.shortcuts import render , render_to_response , redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.template import RequestContext, loader
from django.apps import apps
import collections
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.contenttypes.models import ContentType
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION
from DB.forms import GetModelForm
from DB.funktionenDB import kategorienListe, felderAuslesen, verbundeneElemente, httpOutput
from django.conf import settings
import json
from django.db import connection

def resetidseq(request,app_name,tabelle_name):
	# Ist der User Angemeldet?
	if not request.user.is_authenticated():
		return redirect('dioedb_login')
	# Gibt es die Tabelle?
	try : amodel = apps.get_model(app_name, tabelle_name)
	except LookupError : return HttpResponseNotFound('<h1>Tabelle "'+tabelle_name+'" nicht gefunden!</h1>')
	# Reset id sequence
	try:
		cursor = connection.cursor()
		cursor.execute("SELECT setval('\""+amodel._meta.app_label+"_"+amodel._meta.object_name+"_id_seq\"',  (SELECT MAX(id) FROM \""+amodel._meta.app_label+"_"+amodel._meta.object_name+"\")+1, FALSE)")
		success = json.dumps({'success':'success',})
	except Exception as e:
		success = json.dumps({'error':str(type(e))+' - '+str(e),})
	return httpOutput(success, mimetype='application/json')

# Startseite - Übersicht über alle verfügbaren Tabellen
def start(request):
	info = ''
	# Ist der User Angemeldet?
	if not request.user.is_authenticated():
		return redirect('dioedb_login')

	# Liste der verfuegbaren Tabellen:
	tabellen = collections.OrderedDict()
	applist = settings.DIOEDB_APPLIST
	for aapp in applist:
		if request.user.has_perm(aapp+'.edit'):
			tabellen[aapp] = []
			for model in apps.get_app_config(aapp).models.items():
				amodel = apps.get_model(aapp, model[0])
				if str(model[0])[:4]!='sys_':
					tabellen[aapp].append({'model':model[0],'titel':amodel._meta.verbose_name_plural,'count':amodel.objects.count()})
	# Ausgabe der Seite
	return render_to_response('DB/start.html',
		RequestContext(request, {'tabellen':(tabellen.items()),'database':settings.DATABASES['default']['ENGINE'],'info':info}),)


# Ansicht - Übersicht über Tabelleneinträge mit Option zum bearbeiten
def view(request,app_name,tabelle_name):
	info = ''
	error = ''
	# Ist der User Angemeldet?
	if not request.user.is_authenticated():
		return redirect('dioedb_login')

	# Gibt es die Tabelle?
	try : amodel = apps.get_model(app_name, tabelle_name)
	except LookupError : return HttpResponseNotFound('<h1>Tabelle "'+tabelle_name+'" nicht gefunden!</h1>')

	# Liste der Buchstaben mit Anzahl der Elemente
	if 'getlmfal' in request.POST:
		# print(kategorienListe(amodel))
		return render_to_response('DB/lmfal.html',
			RequestContext(request, {'kategorien_liste':kategorienListe(amodel).items(),'appname':app_name,'tabname':tabelle_name,'info':info,'error':error}),)

	# Liste der Einträge des jeweiligen Buchstaben ausgeben
	if 'getlmfadl' in request.POST:
		return render_to_response('DB/lmfadl.html',
			RequestContext(request, {'lmfadl':kategorienListe(amodel,inhalt=request.POST.get('getlmfadl')),'info':info,'error':error}),)

	# Reine View des Tabelleneintrags !!!
	if 'gettableview' in request.POST:
		aElement = amodel.objects.get(pk=request.POST.get('gettableview'))
		return render_to_response('DB/view_table.html',
			RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'fields':felderAuslesen(aElement,1),'usedby':verbundeneElemente(aElement),'amodel_meta':amodel._meta,'info':info,'error':error}),)

	# Reine View der Verweisliste!
	if 'getverweisliste' in request.POST:
		aElement = amodel.objects.get(pk=request.POST.get('getverweisliste'))
		return render_to_response('DB/view_table_verweisliste.html',
			RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'usedby':verbundeneElemente(aElement,aField=request.POST.get('fieldname'),aMax=0),'amodel_meta':amodel._meta,'info':info,'error':error}),)

	# Ausgabe der Standard Seite mit geladenen Tabelleneintrag !
	if 'loadpk' in request.POST:
		aElement = amodel.objects.get(pk=request.POST.get('loadpk'))
		acontent = render_to_response('DB/view_table.html',
			RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'fields':felderAuslesen(aElement,1),'usedby':verbundeneElemente(aElement),'amodel_meta':amodel._meta,'info':info,'error':error}),).content
		return render_to_response('DB/view.html',
			RequestContext(request, {'kategorien_liste':kategorienListe(amodel,mitInhalt=int(request.POST.get('loadpk')),arequest=request).items(),'appname':app_name,'tabname':tabelle_name,'amodel_meta':amodel._meta,'acontent':acontent,'amodel_count':amodel.objects.count(),'info':info,'error':error}),)

	# Reines Formular des Tabelleneintrags
	if 'gettableeditform' in request.POST:
		if int(request.POST.get('gettableeditform')) > 0:
			aElement = amodel.objects.get(pk=request.POST.get('gettableeditform'))
			aform = GetModelForm(amodel,instance=aElement)
		else:
			aElement = amodel()
			aform = GetModelForm(amodel)
		return render_to_response('DB/edit_table.html',
			RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'amodel_meta':amodel._meta,'aform':aform,'pktitel':aElement._meta.pk.verbose_name,'pkvalue':aElement.pk,'info':info,'error':error}),)

	# Formular ForeignKey Select
	if 'getforeignkeysel' in request.POST:
		try:
			aElement = amodel.objects.get(pk=request.POST.get('getforeignkeysel'))
			acontent = render_to_response('DB/view_table.html',
				RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'fields':felderAuslesen(aElement,1),'usedby':verbundeneElemente(aElement),'amodel_meta':amodel._meta,'info':info,'error':error}),).content
			return render_to_response('DB/foreignkeysel.html',
				RequestContext(request, {'kategorien_liste':kategorienListe(amodel,mitInhalt=int(request.POST.get('getforeignkeysel')),arequest=request).items(),'appname':app_name,'tabname':tabelle_name,'amodel_meta':amodel._meta,'acontent':acontent,'info':info,'error':error}),)
		except ObjectDoesNotExist:
			return render_to_response('DB/foreignkeysel.html',
				RequestContext(request, {'kategorien_liste':kategorienListe(amodel).items(),'appname':app_name,'tabname':tabelle_name,'amodel_meta':amodel._meta,'acontent':'','info':info,'error':error}),)

	# Formular speichern
	if 'saveform' in request.POST and request.user.has_perm(app_name+'.edit'):
		# Neues Formular speichern !!!!!!!!!
		if int(request.POST.get('savepk')) > 0:
			aElement = amodel.objects.get(pk=request.POST.get('savepk'))
			aform = GetModelForm(amodel,request.POST,instance=aElement)
		else:
			aElement = amodel()
			aform = GetModelForm(amodel,request.POST)
		if aform.is_valid():
			aElement = aform.save()
			LogEntry.objects.log_action(
				user_id = request.user.pk,
				content_type_id = ContentType.objects.get_for_model(aElement).pk,
				object_id = aElement.pk,
				object_repr = str(aElement),
				action_flag = CHANGE if int(request.POST.get('savepk')) > 0 else ADDITION
			)
			info = 'Datensatz gespeichert.'
			return render_to_response('DB/view_table.html',
				RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'fields':felderAuslesen(aElement,1),'usedby':verbundeneElemente(aElement),'amodel_meta':amodel._meta,'info':info,'error':error}),)
		else:
			error = 'Fehlerhafte Eingabe!'
		return render_to_response('DB/edit_table.html',
			RequestContext(request, {'aelement':aElement,'aelementapp':aElement._meta.app_label,'aelementtabelle':aElement.__class__.__name__,'amodel_meta':amodel._meta,'aform':aform,'pktitel':aElement._meta.pk.verbose_name,'pkvalue':aElement.pk,'info':info,'error':error}),)
	# Element loeschen
	if 'delobj' in request.POST and request.user.has_perm(app_name+'.edit'):
		aElement = amodel.objects.get(pk=request.POST.get('delobj'))
		error = str(aElement)+' (PK: '+str(aElement.pk)+') wurde geloescht!'
		aElement.delete()
		LogEntry.objects.log_action(
			user_id = request.user.pk,
			content_type_id = ContentType.objects.get_for_model(aElement).pk,
			object_id = aElement.pk,
			object_repr = str(aElement),
			action_flag = DELETION
		)
		return render_to_response('DB/view_empty.html',
			RequestContext(request, {'amodel_meta':amodel._meta,'appname':app_name,'tabname':tabelle_name,'info':info,'error':error}),)


	# Ausgabe der Standard Seite
	return render_to_response('DB/view.html',
		RequestContext(request, {'kategorien_liste':kategorienListe(amodel).items(),'appname':app_name,'tabname':tabelle_name,'amodel_meta':amodel._meta,'amodel_count':amodel.objects.count(),'info':info,'error':error}),)

# Suche
def search(request):
	info = ''
	# Ist der User Angemeldet?
	if not request.user.is_authenticated():
		return redirect('dioedb_login')

	# Nach OpenStreetMap Orten in der tbl_orte suchen ...
	if 'sucheorte' in request.POST:
		suchorte = json.loads(request.POST.get('suchorte'))
		ortModel = apps.get_model('pab', 'tbl_orte')
		for suchort in suchorte:
			print(suchort['osm_id']+' - '+suchort['osm_type'])
			try:
				ortObjekt = ortModel.objects.filter(osm_id=suchort['osm_id'],osm_type=suchort['osm_type']).order_by('pk').first()
				suchort['ort_pk'] = ortObjekt.pk
			except:
				pass
		return httpOutput('OK'+json.dumps(suchorte))

	# Nach Ort in der tbl_orte suchen und als Json ausgeben
	if 'getort' in request.POST:
		ortData = {}
		ortModel = apps.get_model('pab', 'tbl_orte')
		try:
			ortObjekt = ortModel.objects.get(pk=request.POST.get('getort'))

app/DB/templates/DB/auswertung_start.html
{% extends 'main/basis.html' %}
{% load staticfiles %}{% load dioeTags %}
{% block title %} - Übersicht aller Auswertungsmöglichkeiten{% endblock %}
{% block ueberschrift %} - Übersicht aller Auswertungsmöglichkeiten{% endblock %}
{% block inhalt %}

<h2>Übersicht aller Auswertungsmöglichkeiten</h2>
{% if info %}<div class="alert alert-info">{{ info|safe }}</div>{% endif %}
{% if error %}<div class="alert alert-danger">{{ error|safe }}</div>{% endif %}
<br>

<div class="row">
	<div class="col-md-3">
		{% for aauswertung in auswertungen %}
			<a href="#" data-auswertung="{{ aauswertung.id }}" class="btn btn-primary mib5 w100 fx-btn-badge select-auswertung">{{ aauswertung.titel }}<span class="badge">{{ aauswertung.count }}</span></a>
		{% endfor %}
	</div>
</div>

{% endblock %}
{% block sitejs %}
<script>
	var csrf='{{ csrf_token }}';
	var isstartseite = {% if request.path == startseiteurl %}true{% else %}false{% endif %};
	var sysstatusurl = "{% url 'sysstatus' %}";
	var asurl='{{ asurl }}';
</script>
<script src="{% static "db/js/auswertung_scripts.js" %}?{% settings_value "CACH_RANDOM" %}"></script>
{% endblock %}

app/DB/templates/DB/auswertung_view.html
{% extends 'main/basis.html' %}
{% load staticfiles %}{% load dioeTags %}
{% block title %} - Auswertung: {{ aauswertung.titel }}{% endblock %}
{% block ueberschrift %} - Auswertung: {{ aauswertung.titel }}n{% endblock %}
{% block inhalt %}

<h2>Auswertung: {{ aauswertung.titel }} <span style="font-size:18px;">({{ aauswertung.allcount }} Einträge)</span></h2>
{% if info %}<div class="alert alert-info">{{ info|safe }}</div>{% endif %}
{% if error %}<div class="alert alert-danger">{{ error|safe }}</div>{% endif %}

<div id="view-auswertung" data-auswertung="{{ aauswertung.id }}">
<div id="control-auswertung">
	{% if aauswertung.filter %}
		<h4>Filter:</h4>
		{% for afilterline in aauswertung.filter %}
			<div class="filterline-auswertung form-inline">
				{% for afilter in afilterline %}
					<div class="form-group">
						<label for="fid-{{ afilter.id }}">{% firstof afilter.verbose_name afilter.field %}</label>
						{% if afilter.type = "select" %}
							<select id="fid-{{ afilter.id }}" data-filter-id="{{ afilter.id }}"{% if afilter.needID %} data-filter-needid="#fid-{{ afilter.needID }}"{% endif %} class="form-control">
								<option value="0">Alle</option>
								{% for aoption in afilter.modelQuery %}
									<option value="{{ aoption.pk|stringformat:"i" }}"{% if aoption.pk == afilter.val %} selected{% endif %}>{{ aoption }}</option>
								{% endfor %}
							</select>
						{% else %}
							{{ afilter }}<hr>
						{% endif %}
					</div>
				{% endfor %}
			</div>
		{% endfor %}
	{% endif %}
</div>
<br>
{%include "DB/auswertung_datalist.html" %}
</div>
<br>
<br>
<br>
{% endblock %}
{% block sitejs %}
<script>
	var csrf='{{ csrf_token }}';
	var isstartseite = {% if request.path == startseiteurl %}true{% else %}false{% endif %};
	var sysstatusurl = "{% url 'sysstatus' %}";
	var asurl='{{ asurl }}';
</script>
<script src="{% static "db/js/auswertung_scripts.js" %}?{% settings_value "CACH_RANDOM" %}"></script>
{% endblock %}

app/DB/templates/DB/csv_view.html
{% load staticfiles %}
{% load dioeTags %}
<div class="modal-title"><b>{{ asysid.datei }}</b> - {{ asysid.zeit }}{% if asysid.erledigt %} - Erledigt!{% endif %} <button class="show-hide-unused-cols" title="Erweiterte Ansicht an/aus" style="margin-right:25px;font-size:16px;"><span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span></button></div>
<div class="modal-body">
{% if error %}<div class="alert alert-danger">{{ error|safe }}</div>{% endif %}
{% if warning %}<div class="alert alert-warning">{{ warning|safe }}</div>{% endif %}
{% if info %}<div class="alert alert-info mh300px hscroller vscroller" style="white-space:nowrap;">{{ info|safe }}</div>{% endif %}
{% if csvData %}
	<div class="table-responsive">
		<table class="table table-bordered table-hover hide-unused-cols">
			<thead class="table-nowrap">
				<tr>
					<th class="coluse">#</th>
					{% for cell in csvData.colDef %}
						{% with colError=csvData.colError|get_item:cell %}
							<th class="{% if cell in csvData.colUse %}coluse{% if colError %} danger{% else %} success{% endif %}{% endif %}" {% if colError %} title="{% for key,aError in colError.items %}{{aError}}&#13;{% endfor %}"{% endif %}>{{ cell }}</th>
						{% endwith %}
					{% endfor %}
				</tr>
			</thead>
		{% for row in csvData.dispRows %}
			<tr>
				<td class="coluse">{{ row.nr }}</td>
				{% for aCellDef in csvData.colDef %}
					{% with cell=row.cols|get_item:aCellDef %}
						<td{% if aCellDef in csvData.colUse %} class="coluse{% if cell.error %} danger{% endif %}"{% endif %} title="{{ aCellDef }}{% if 'orgValue' in cell %} - Original Wert: '{{ cell.orgValue }}'{% endif %}{% if cell.conTable %} - Verbundene Tabelle: {{ cell.conTable }}{% endif %}{% if cell.error %}&#13;{{ cell.error }}{% endif %}">
							{{ cell.value }}
						</td>
					{% endwith %}
				{% endfor %}
			</tr>
		{% endfor %}
		<tr><td>...</td>{% for cell in csvData.colDef %}<td>...</td>{% endfor %}</tr>
		</table>
	</div>
{% else %}
<b>Keine Importdaten!!!</b>
{% endif %}
</div>
<div class="modal-footer">
	{% if not hasError %}
		<button type="button" class="btn btn-primary csvdateiselectimport" data-pk="{{ asysid.pk }}">Importieren</button>
	{% endif %}
	<button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
</div>

app/DB/templates/DB/dateien.html
<div class="dateien" data-verzeichniss="{{ verzeichniss }}">
	<div class="dateientopline clearfix">
		<h4>Dateien:</h4>
		{% if permission > 2 %}<button class="dateien-neuesverzeichniss" title="Verzeichniss hinzufügen"><span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span></button>{% endif %}
		{% if permission > 1 %}
			<button class="dateien-hochladen" title="Datei hochladen"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span> </button>
			<form id="dateienuploadform" action="{% url 'DB:dateien' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<input type="hidden" name="upload" id="dateienuploadverzeichniss" value="{{ verzeichniss }}">
				<input type="file" name="dateien" id="dateienupload" multiple style="display: none;">
			</form>
		{% endif %}
	</div>
	<br>
	{% if dateien and permission > 0 %}
		<div class="dateienliste">
			<div class="row">
				{% for datei in dateien %}
					<div class="col-md-3"><div class="fileobject">
						<a class="filelink" href="{{ datei.link }}" target="_blank" data-file-name="{{ datei.name }}" data-file-fullpath="{{ datei.fullpath }}" data-file-type="{{ datei.type }}">
							{% if datei.prvImg %}
								<div class="fileimgc"><img src="{{ datei.prvImg }}"></div>
							{% endif %}
							<span class="filetype">{{ datei.type }}</span><span class="filesize">{{ datei.size|filesizeformat }}</span>
						</a>
						{{ datei.name }}<br>
						{{ datei.lmod|date:"d.m.Y" }} - {{ datei.lmod|time:"H:i" }} Uhr <button class="dateien-dateien dateien-dateiumbenennen" title="Datei umbennenen"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button> <button class="dateien-dateien dateien-dateiloeschen" title="Datei löschen"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
					</div><br></div>
					{% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
				{% endfor %}
			</div>
		</div>
	{% else %}
		<div>Keine Dateien</div>
	{% endif %}
	<div id="dateiuploadfortschritt">
		<div class="text">Upload ...</div>
		<div class="progress"><div class="progress-bar progress-bar-striped active" role="progressbar" style="width: 0%;">0 %</div></div>
	</div>
</div>

app/DB/templates/DB/dateien_start.html
{% extends 'main/basis.html' %}
{% load staticfiles %}
{% load dioeTags %}
{% load crispy_forms_tags %}
{% block sitecss %}<link href="{% static "db/css/dateien.css" %}?{% settings_value "CACH_RANDOM" %}" rel="stylesheet">{% endblock %}
{% block title %} - Maske{% endblock %}
{% block ueberschrift %} - Maske{% endblock %}
{% block inhalt %}
<div class="row h100">
	<div class="col-md-3 h100 mh200px vscroller filetreerow">
		<h4>Verzeichnisse:</h4>
		<div class="filetree">
		{% with sdir=tree template_name="DB/dateien_tree.html" %}{% include template_name %}{% endwith %}
		</div>
	</div>
	<div class="col-md-9 h100 mh600px" style="border-right:1px solid #eee;padding:0px;"><div class="h100 mcon vscroller">
		{% if info %}<div class="alert alert-info">{{ info|safe }}</div>{% endif %}
		{% if error %}<div class="alert alert-danger">{{ error|safe }}</div>{% endif %}
	</div></div>
</div>
<style>
	html,body,body>.container { height:100%; }
</style>
{% endblock %}
{% block sitejs %}
<script>
	var csrf='{{ csrf_token }}';
	var audiodir = '{% settings_value "AUDIO_URL" %}';
</script>
<script src="{% static "db/js/dateien_funktionen.js" %}?{% settings_value "CACH_RANDOM" %}"></script>
<script src="{% static "db/js/dateien.js" %}?{% settings_value "CACH_RANDOM" %}"></script>
{% endblock %}